### ISSUE TITLE
DDPG is on-policy?

### ISSUE THREAD

**Issue by hashbangCoder** [yenchenlin1994/DeepLearningFlappyBird#17]
Hi,
For the ddpg.py code, I assume you're following [this](http://arxiv.org/pdf/1509.02971v5.pdf) paper by Silver et. al.  
If so, your algorithm doesn't appear to match theirs. Theirs is a off-policy approach due to added noise specifically an [OU](https://en.wikipedia.org/wiki/Ornstein%E2%80%93Uhlenbeck_process) process . From what I understand, you're using an on-policy approach [here](https://github.com/rllab/rllab/blob/b5e1946c9e4e8231398e5982f2d2c01fb74043ad/rllab/algos/ddpg.py#L331) which has no exploration potential for the actor. If you're following a stochastic policy by using the last layer output as a distribution, doesn't that defeat the purpose of DDPG?
Am I missing something?

**Comment by yenchenlin1994** [comment]
wrong place haha ;)
