### ISSUE TITLE
Crashes on launch on Mac

### ISSUE THREAD

**Issue by imikay** [yenchenlin1994/DeepLearningFlappyBird#6]
Hi,

DeepLearningFlappyBird crashes on launch on Mac OS X EI Captian, here is the error log:

> tensorflow.python.framework.errors.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-30000

**Comment by yenchenlin1994** [comment]
Hello, I developed it on Mac OS, and it still works well for me.
What's your TensorFlow version?

**Comment by imikay** [comment]
The version of TensorFlow is 0.5.0

> $ pip show tensorflow
> ---
> Metadata-Version: 2.0
> Name: tensorflow
> Version: 0.5.0
> Summary: TensorFlow helps the tensors flow
> Home-page: http://tensorflow.com/
> Author: Google Inc.
> Author-email: opensource@google.com
> License: Apache 2.0
> Location: /usr/local/lib/python2.7/site-packages
> Requires: six, numpy
> Classifiers:
>   Development Status :: 4 - Beta
>   Intended Audience :: Developers
>   Intended Audience :: Education
>   Intended Audience :: Science/Research
>   License :: OSI Approved :: Apache Software License
>   Programming Language :: Python :: 2.7
>   Topic :: Scientific/Engineering :: Mathematics
>   Topic :: Software Development :: Libraries :: Python Modules
>   Topic :: Software Development :: Libraries
> Entry-points:
>   [console_scripts]
>   tensorflow_model_cifar10_eval = tensorflow.models.image.cifar10.cifar10_eval:main
>   tensorflow_model_cifar10_multi_gpu_train = tensorflow.models.image.cifar10.cifar10_multi_gpu_train:main
>   tensorflow_model_cifar10_train = tensorflow.models.image.cifar10.cifar10_train:main
>   tensorboard = tensorflow.tensorboard.tensorboard:main
>   tensorflow_model_mnist_convolutional = tensorflow.models.image.mnist.convolutional:main

**Comment by imikay** [comment]
Hi, 
Should I  upgrade my TensorFlow version? The current version is 0.7, should I use this version instead?

**Comment by yenchenlin1994** [comment]
Yes please, see this relevant PR #2

**Comment by yenchenlin1994** [comment]
I've updated the README, this project may need TensorFlow 0.7

**Comment by imikay** [comment]
Ok, thanks.

**Comment by yenchenlin1994** [comment]
If this works, would you please close this issue?
Thanks.

**Comment by imikay** [comment]
Sure.

**Comment by imikay** [comment]
It works now after I upgraded to TensorFlow 0.7, thanks.

**Comment by yenchenlin1994** [comment]
:+1:
